### ISSUE TITLE
statcounter.com tracking image

### ISSUE THREAD

**Issue by Marcono1234** [MinecraftIRC/MinecraftHopper#5]
[Multiple pages](https://github.com/MinecraftIRC/MinecraftHopper/search?q=statcounter.com&unscoped_q=statcounter.com) embed an invisible image to track visits.

Is this still needed?
If so, then the protocol would need to be changed from HTTP to HTTPS because the hopper site is served using HTTPS.

**Comment by LordRalex** [comment]
Resolved
